# Generated by Django 5.2.3 on 2025-06-23 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(max_length=255)),
                ("car_number", models.CharField(max_length=255)),
                ("car_color", models.CharField(max_length=255)),
                ("car_year", models.IntegerField()),
                ("car_type", models.CharField(max_length=255)),
                ("car_image", models.ImageField(upload_to="car_images/")),
                ("litsency_driver", models.FileField(upload_to="driver_litsency/")),
                ("tex_litsency", models.FileField(upload_to="tex_litsency/")),
                ("card_number", models.IntegerField()),
                ("card_period", models.IntegerField()),
                ("telegram_nik", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("pasport", models.FileField(upload_to="pasports/")),
                ("password", models.CharField(max_length=255)),
                ("pasport_seria", models.CharField(max_length=200)),
                (
                    "is_who",
                    models.CharField(
                        choices=[
                            ("shipper", "shippper"),
                            ("broker", "broker"),
                            ("carier", "carier"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Validatedcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqamini +9989XXXXXXXX kabi kiriting!",
                                regex="d{0,9}",
                            )
                        ],
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Kodni kiritishlar soni:"),
                ),
                (
                    "validated",
                    models.BooleanField(
                        default=False,
                        help_text="Shaxsiy kabinetingizni yaratishingiz mumkin!",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=9, unique=True)),
                ("verify_code", models.SmallIntegerField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "step_reset",
                    models.CharField(
                        blank=True,
                        choices=[("send", "send"), ("confirmed", "confirmed")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "step_change_phone",
                    models.CharField(
                        blank=True,
                        choices=[("send", "send"), ("confirmed", "confirmed")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="order_images/")),
                ("descriptions", models.TextField()),
                (
                    "from_place",
                    models.CharField(
                        choices=[
                            ("Toshkent", "Toshkent"),
                            ("Navoiy", "Navoiy"),
                            ("Buxoro", "Buxoro"),
                            ("Samarqand", "Samarqand"),
                            ("Jizzax", "Jizzax"),
                            ("Xorazm", "Xorazm"),
                            ("Sirdaryo", "Sirdaryo"),
                            ("Namangan", "Namangan"),
                            ("Farg'ona", "Farg'ona"),
                            ("Andijon", "Andijon"),
                            ("Qashqadaryo", "Qashqadaryo"),
                            ("Surxandaryo", "Surxandaryo"),
                            ("Nukus", "Nukus"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "to_place",
                    models.CharField(
                        choices=[
                            ("Toshkent", "Toshkent"),
                            ("Navoiy", "Navoiy"),
                            ("Buxoro", "Buxoro"),
                            ("Samarqand", "Samarqand"),
                            ("Jizzax", "Jizzax"),
                            ("Xorazm", "Xorazm"),
                            ("Sirdaryo", "Sirdaryo"),
                            ("Namangan", "Namangan"),
                            ("Farg'ona", "Farg'ona"),
                            ("Andijon", "Andijon"),
                            ("Qashqadaryo", "Qashqadaryo"),
                            ("Surxandaryo", "Surxandaryo"),
                            ("Nukus", "Nukus"),
                        ],
                        max_length=255,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "ordertype",
                    models.CharField(
                        choices=[
                            ("sinuvchan", "sinuvchan"),
                            ("yonuvchan", "yonuvchan"),
                        ],
                        max_length=250,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.driver"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
