# Generated by Django 5.2.3 on 2025-06-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
